
language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      python: "3.6"
      env: PIP=pip

    - os: linux
      python: "2.7"
    - os: linux
      python: "3.4"
    - os: linux
      python: "3.5"
    - os: linux
      python: "3.6"

    - os: osx
      sudo: required
      language: generic
      env: PYTHON=2
    - os: osx
      sudo: required
      language: generic
      env: PYTHON=3
    - os: osx
      language: generic
      env: PIP=pip2

install: |
  if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    brew update
    if [[ $PYTHON == 3 ]]; then
        brew upgrade python
    fi
    python$PYTHON -m pip install virtualenv
    python$PYTHON -m venv venv
    source venv/bin/activate
    cd pyat
    pip$PYTHON install --upgrade pip setuptools wheel
    pip$PYTHON install --only-binary=numpy,scipy -r requirements.txt
    python$PYTHON setup.py install
  else
    cd pyat
    pip install --upgrade pip setuptools wheel
    pip install --only-binary=numpy,scipy -r requirements.txt
    python setup.py install
  fi

script:
 - py.test test
 - python -m pip install cibuildwheel
 - python -m pip install --upgrade cibuildwheel
 - python -m pip wheel -r requirements.txt
 - python -m pip wheel -r requirements.txt -w /home/travis/build/T-Nicholls/at/pyat/wheelhouse
 - python -m pip wheel -r requirements.txt -w ~/build/T-Nicholls/at/pyat/wheelhouse
 - python -m pip wheel -r requirements.txt -w /home/travis/build/T-Nicholls/at/pyat/wheelhouse --no-deps
 - python -m pip wheel /home/travis/build/T-Nicholls/at/pyat/requirements.txt -w /tmp/built_wheel --no-deps
 - python -m pip wheel /home/travis/build/T-Nicholls/at/pyat -w /tmp/built_wheel --no-deps
 - python -m pip wheel /home/travis/build/T-Nicholls/at/pyat -w /tmp/built_wheel --no-deps
 - python -m cibuildwheel --output-dir wheelhouse

