
language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: BUILD_WHEEL="1"
    - os: linux
      python: "2.7"
    - os: linux
      python: "3.4"
    - os: linux
      python: "3.5"
    - os: linux
      python: "3.6"

    - os: osx
      sudo: required
      language: generic
      env: PYTHON=2
    - os: osx
      sudo: required
      language: generic
      env: PYTHON=3
    - os: osx
      language: generic
      env: BUILD_WHEEL="1"

install: |
  if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    brew update
    if [[ $PYTHON == 3 ]]; then
        brew upgrade python
    fi
    python$PYTHON -m pip install virtualenv
    python$PYTHON -m venv venv
    source venv/bin/activate
    cd pyat
    pip$PYTHON install --upgrade pip setuptools wheel
    pip$PYTHON install --only-binary=numpy,scipy -r requirements.txt
    python$PYTHON setup.py install
  else
    cd pyat
    pip install --upgrade pip setuptools wheel
    pip install --only-binary=numpy,scipy -r requirements.txt
    python setup.py install
  fi

script:
 - python setup.py bdist_wheel
 - python -m pip wheel . -w /tmp/built_wheel --no-deps
 - |
   if [[$BUILD_WHEEL == 1]]; then
     pip3 install --upgrade cibuildwheel;
     export CIBW_BUILD_VERBOSITY='3';
     export CIBW_BEFORE_BUILD='pip install numpy';
     cibuildwheel --output-dir wheelhouse;
   else
     py.test test;
   fi
