
language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

script:
  - cd pyat
  - export CIBW_BUILD_VERBOSITY='3';
  - export CIBW_BEFORE_BUILD='pip install numpy';
  - $PIP install cibuildwheel==0.10.0
  - cibuildwheel --output-dir wheelhouse
