name: Publish distribution to Test PyPI

on:
  push:
    tags:
      - pyat-*

defaults:
  run:
    working-directory: ./pyat

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        run: |
          python -m pip install -r requirements.txt
          python -m cibuildwheel --output-dir wheelhouse

