name: Publish distribution to Test PyPI

on:
  push:
    tags:
      - pyat-*


defaults:
  run:
    working-directory: ./pyat


jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.7.4

      #- name: Remove built files
      #  if: (! contains(matrix.os, 'windows'))
      #  run: rm -rf build

      - name: Upgrade setuptools
        run: python -m pip install --upgrade setuptools

      - name: Prepare source
        run: |
          python -m pip install numpy==1.14.3
          python setup.py build
      #    rm -rf build

      #- name: Install dependencies
      #  run: #python -m pip install -r requirements.txt

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_SKIP: cp39-*
          CIBW_BEFORE_BUILD: pip install --upgrade setuptools; pip install numpy==1.14.3; pwd; ls -al; ls -al /project
          CIBW_BUILD_VERBOSITY: 1

